baseURL = "/"
languageCode = "en-uk"
title = "Hello, I'm Arcade 😊"
theme = "hello-friend-ng"
paginate = 10

[permalinks]
    posts = "posts/:year/:month/:title/"

[author]
    name = "Arcade Coder"

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    # Subtitle for home
    homeSubtitle = "Programmer & Technical writer"

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts = false

    # Enable sharing buttons, if you linke
    enableSharingButtons = true

    # Metadata mostly used in document's head
    description = "My new homepage or blog"
    keywords = "homepage, blog"
    images = [""]

    # Default theme "light" or "dark"
    defaultTheme = "dark"
[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hello, I'm Arcade 😊🎮"
    subtitle = ""
    keywords = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd/home/Arcade/Coder"
      logoHomeLink = "/"
    # or
    #
    #path = "/img/me.JPG"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

[params.logo]
    logoText     = "$ cd/home/Arcade Coder"
    logoHomeLink = "/"

    [params.portrait]
    path    = "/img/me.png"
    alt     = "Portrait"
    maxWidth = "100px"

[[params.social]]
    name = "twitter"
    url = "https://twitter.com/arcadecoder"

[[params.social]]
    name = "medium"
    url = "https://medium.com/@arcadecoder"

[[params.social]]
    name = "dev"
    url = "https://dev.to/arcadecoder"

[[params.social]]
    name = "github"
    url  = "https://github.com/arcadecoder"

[[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/arcade-k-63a62b101/"

[[params.social]]
    name = "instagram"
    url = "https://www.instagram.com/arcadecoder/"

[[params.social]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/users/11055600/arcade"

[menu]
  [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "posts/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true